### ISSUE TITLE
 Error with bot when Run AddMeFast script

### ISSUE THREAD

**Issue by km1273551** [asimptot/FollowerBot#32]
Hi, I have this error, could you help me?
![Capture](https://user-images.githubusercontent.com/38248193/212209917-661bdece-ba3a-4476-a2c6-b494f40b0f7b.PNG)

**Comment by asimptot** [comment]
@km1273551 hi,

Some users don't see cookies page on Facebook login. Can you add ''' characters between those parts and run it again?

'''
        cookies = WebDriverWait(self.browser, 10).until(
            EC.presence_of_element_located((By.CLASS_NAME, '_9xo5'))
        )
        cookies.click()
        sleep(5)
'''

**Comment by km1273551** [comment]
thank you it works but Another Error appeared and when login in Gmail This message appears Something went wrong in Gmail login process.
![2](https://user-images.githubusercontent.com/38248193/212350062-8aa7c6b3-95ef-4867-844b-84f657c4ec8e.PNG)

**Comment by asimptot** [comment]
@km1273551 hi,

Unfortunatelly, you can't run gmail task in headless mode due to Google restriction. You should run it in non-headless mode.

**Comment by km1273551** [comment]
Ok, How run it play in headless mode? 
Thank you.

**Comment by asimptot** [comment]
Please add # character to 14th line in https://github.com/asimptot/FollowerBot/blob/main/init.py 

#chrome_options.add_argument('--headless')

**Comment by km1273551** [comment]
> Please add # character to 14th line in https://github.com/asimptot/FollowerBot/blob/main/init.py
> 
> #chrome_options.add_argument('--headless')

I noticed when getting credit when registering on the OKRU site, the error shown in the picture occurs due to It is prohibited in our country
So how can I cancel it during registration?
![3](https://user-images.githubusercontent.com/38248193/212428213-bbbfeb6a-e72b-4212-a488-7d587fc7af23.PNG)

**Comment by asimptot** [comment]
If you mean how to cancel ok.ru task, you should remove in the following lines from the code.

amf.login_okru()
amf.okru_join

**Comment by sbironx** [comment]
now it works, thank you bro

**Comment by arham837** [comment]
gmail is still not working in non headless mode.

**Comment by asimptot** [comment]
> gmail is still not working in non headless mode.

What kind of error did you get?

**Comment by arham837** [comment]
SAme error as before that something went wrong while login gmail

**Comment by asimptot** [comment]
Can you please send a screenshot of your browser?

**Comment by arham837** [comment]
This error is comming 
https://ibb.co/9c67LXk

**Comment by asimptot** [comment]
You should use this init.py file to pass this screen. Otherwise Google blocks your attemption.

https://github.com/asimptot/FollowerBot/blob/main/init.py

**Comment by arham837** [comment]
now giving this error
python: can't open file 'C:\\Users\\Asus\\Downloads\\Compressed\\FollowerBot-main\\FollowerBot-main\\get_credit_on_AddMeFast': [Errno 2] No such file or directory

C:\Users\Asus\Downloads\Compressed\FollowerBot-main\FollowerBot-main>python get_credit_on_AddMeFast.py
Traceback (most recent call last):
  File "C:\Users\Asus\Downloads\Compressed\FollowerBot-main\FollowerBot-main\get_credit_on_AddMeFast.py", line 958, in <module>
    amf.setup()
  File "C:\Users\Asus\Downloads\Compressed\FollowerBot-main\FollowerBot-main\get_credit_on_AddMeFast.py", line 9, in setup
    Setup.init(self)
  File "C:\Users\Asus\Downloads\Compressed\FollowerBot-main\FollowerBot-main\init.py", line 15, in init
    self.browser = uc.Chrome(options=chrome_options, version_main=108)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 429, in __init__
    super(Chrome, self).__init__(
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 80, in __init__
    super().__init__(
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 104, in __init__
    super().__init__(
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 715, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:64577
from session not created: This version of ChromeDriver only supports Chrome version 108
Current browser version is 110.0.5481.77
Stacktrace:
Backtrace:
        (No symbol) [0x006CF243]
        (No symbol) [0x00657FD1]
        (No symbol) [0x0054D04D]
        (No symbol) [0x0056F6B4]
        (No symbol) [0x00568424]
        (No symbol) [0x00568201]
        (No symbol) [0x0059F056]
        (No symbol) [0x0059EB2A]
        (No symbol) [0x00598386]
        (No symbol) [0x0057163C]
        (No symbol) [0x0057269D]
        GetHandleVerifier [0x00969A22+2655074]
        GetHandleVerifier [0x0095CA24+2601828]
        GetHandleVerifier [0x00778C0A+619850]
        GetHandleVerifier [0x00777830+614768]
        (No symbol) [0x006605FC]
        (No symbol) [0x00665968]
        (No symbol) [0x00665A55]
        (No symbol) [0x0067051B]
        BaseThreadInitThunk [0x76097D69+25]
        RtlInitializeExceptionChain [0x7744BB9B+107]
        RtlClearBits [0x7744BB1F+191]

Exception ignored in: <function Chrome.__del__ at 0x0000023478BBD260>
Traceback (most recent call last):
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 769, in __del__
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 758, in quit
OSError: [WinError 6] The handle is invalid

**Comment by asimptot** [comment]
I have no clue how to fix it. It seems caused by your setup. You should update version main --> 108, 109 etc.

self.browser = uc.Chrome(options=chrome_options, version_main=108)
