### ISSUE TITLE
Not working shows this

### ISSUE THREAD

**Issue by Smitty31** [asimptot/FollowerBot#39]
Traceback (most recent call last):
  File "C:\Users\fsmit\OneDrive\Desktop\FollowerBot-main\get_instagram_followers.py", line 46, in <module>
    ig.setup()
  File "C:\Users\fsmit\OneDrive\Desktop\FollowerBot-main\get_instagram_followers.py", line 13, in setup
    Setup.init(self)
  File "C:\Users\fsmit\OneDrive\Desktop\FollowerBot-main\init.py", line 15, in init
    self.browser = uc.Chrome(options=chrome_options)
  File "C:\Users\fsmit\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\undetected_chromedriver\__init__.py", line 411, in __init__
    browser = subprocess.Popen(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1380, in _execute_child
    args = list2cmdline(args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 563, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\os.py", line 823, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by asimptot** [comment]
@Smitty31 please update your init file as the following.

from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
import warnings
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait

class Setup:
def init(self):
warnings.filterwarnings("ignore")
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--window-size=1036, 674')
chrome_options.add_experimental_option("excludeSwitches", ["enable-automation"])
chrome_options.add_experimental_option('useAutomationExtension', False)
chrome_options.add_argument('--headless')
chrome_options.add_argument("--log-level=3")
chrome_options.add_experimental_option("prefs", {
"profile.default_content_setting_values.notifications": 1
})
self.browser = webdriver.Chrome(executable_path=ChromeDriverManager().install(), options=chrome_options, )

def close_browser(self):
    self.browser.close()

**Comment by a2gx2** [comment]
I did what you told me and now I have this error:
Traceback (most recent call last):
  File "C:\Users\Edit\Desktop\FollowerBot-main\get_instagram_followers.py", line 4, in <module>
    from init import *
  File "C:\Users\Edit\Desktop\FollowerBot-main\init.py", line 11
    def init(self):
    ^
IndentationError: expected an indented block after class definition on line 10
