### ISSUE TITLE
I get this error when running the file

### ISSUE THREAD

**Issue by allexxbog** [asimptot/FollowerBot#45]
Traceback (most recent call last):
  File "C:\Users\all3x\Desktop\instagbot\get_instagram_followers.py", line 46, in <module>
    ig.setup()
  File "C:\Users\all3x\Desktop\instagbot\get_instagram_followers.py", line 13, in setup
    Setup.init(self)
  File "C:\Users\all3x\Desktop\instagbot\init.py", line 15, in init
    self.browser = uc.Chrome(options=chrome_options, version_main=108)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\all3x\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 409, in __init__
    browser = subprocess.Popen(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\all3x\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\all3x\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1433, in _execute_child
    args = list2cmdline(args)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\all3x\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 608, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "<frozen os>", line 824, in fsdecode
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by asimptot** [comment]
Hi,

Did you install libraries?

**Comment by allexxbog** [comment]
Hey, I have fixed it. The libraries werent uppdated. However, I found another thing- the followers sometimes unfollow.

**Comment by asimptot** [comment]
@allexxbog hi,

Yes, it's because Instagram doesn't allow fake accounts to follow any account. There is nothing to fix unfollow problem.
