### ISSUE TITLE
OSError: [WinError 6] The handle is invalid

### ISSUE THREAD

**Issue by triplesix333** [asimptot/FollowerBot#48]
What is your Instagram username?
triplesix_33
Getting followers... Please do not terminate the program.
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\FollowerBot-main\FollowerBot-main\get_instagram_followers.py", line 45, in <module>
    ig.setup()
  File "C:\Users\HP\Desktop\FollowerBot-main\FollowerBot-main\get_instagram_followers.py", line 13, in setup
    Setup.init(self)
  File "C:\Users\HP\Desktop\FollowerBot-main\FollowerBot-main\init.py", line 15, in init
    self.browser = uc.Chrome(options=chrome_options, version_main=108)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 429, in __init__
    super(Chrome, self).__init__(
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 80, in __init__
    super().__init__(
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 104, in __init__
    super().__init__(
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 715, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:62539
from session not created: This version of ChromeDriver only supports Chrome version 108
Current browser version is 110.0.5481.78
Stacktrace:
Backtrace:
        (No symbol) [0x0031F243]
        (No symbol) [0x002A7FD1]
        (No symbol) [0x0019D04D]
        (No symbol) [0x001BF6B4]
        (No symbol) [0x001B8424]
        (No symbol) [0x001B8201]
        (No symbol) [0x001EF056]
        (No symbol) [0x001EEB2A]
        (No symbol) [0x001E8386]
        (No symbol) [0x001C163C]
        (No symbol) [0x001C269D]
        GetHandleVerifier [0x005B9A22+2655074]
        GetHandleVerifier [0x005ACA24+2601828]
        GetHandleVerifier [0x003C8C0A+619850]
        GetHandleVerifier [0x003C7830+614768]
        (No symbol) [0x002B05FC]
        (No symbol) [0x002B5968]
        (No symbol) [0x002B5A55]
        (No symbol) [0x002C051B]
        BaseThreadInitThunk [0x76B66739+25]
        RtlGetFullPathName_UEx [0x77838ACF+1215]
        RtlGetFullPathName_UEx [0x77838A9D+1165]

Exception ignored in: <function Chrome.__del__ at 0x00000250C4EA1DA0>
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 769, in __del__
  File "C:\Users\HP\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 758, in quit
OSError: [WinError 6] The handle is invalid

**Comment by asimptot** [comment]
Hi,

Please write 127 instead of 108. And run it.

self.browser = uc.Chrome(options=chrome_options, version_main=108)
