### ISSUE TITLE
error init.py

### ISSUE THREAD

**Issue by jjharoll** [asimptot/FollowerBot#49]
(env) C:\Users\jharol.perez\Desktop\FollowerBotJYJ1>python get_instagram_followers.py
What is your Instagram username?
jharolperez
Getting followers... Please do not terminate the program.
Traceback (most recent call last):
  File "C:\Users\jharol.perez\Desktop\FollowerBotJYJ1\get_instagram_followers.py", line 46, in <module>
    ig.setup()
  File "C:\Users\jharol.perez\Desktop\FollowerBotJYJ1\get_instagram_followers.py", line 13, in setup
    Setup.init(self)
  File "C:\Users\jharol.perez\Desktop\FollowerBotJYJ1\init.py", line 15, in init
    self.browser = uc.Chrome(options=chrome_options, version_main=127)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jharol.perez\Pictures\FollowerBotJYJ\env\Lib\site-packages\undetected_chromedriver\__init__.py", line 242, in __init__
    patcher.auto()
  File "C:\Users\jharol.perez\Pictures\FollowerBotJYJ\env\Lib\site-packages\undetected_chromedriver\patcher.py", line 127, in auto
    release = self.fetch_release_number()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jharol.perez\Pictures\FollowerBotJYJ\env\Lib\site-packages\undetected_chromedriver\patcher.py", line 148, in fetch_release_number
    return LooseVersion(urlopen(self.url_repo + path).read().decode())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jharol.perez\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jharol.perez\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jharol.perez\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\jharol.perez\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jharol.perez\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\jharol.perez\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
Exception ignored in: <function Patcher.__del__ at 0x0000000006209440>
Traceback (most recent call last):
  File "C:\Users\jharol.perez\Pictures\FollowerBotJYJ\env\Lib\site-packages\undetected_chromedriver\patcher.py", line 273, in __del__     
    time.sleep(0.1)
OSError: [WinError 6] Controlador no válido

(env) C:\Users\jharol.perez\Desktop\FollowerBotJYJ1>python get_instagram_followers.py
What is your Instagram username?
jyj_press_on_nails_colombia
Getting followers... Please do not terminate the program.
Traceback (most recent call last):
  File "C:\Users\jharol.perez\Desktop\FollowerBotJYJ1\get_instagram_followers.py", line 46, in <module>
    ig.setup()
  File "C:\Users\jharol.perez\Desktop\FollowerBotJYJ1\get_instagram_followers.py", line 13, in setup
    Setup.init(self)
  File "C:\Users\jharol.perez\Desktop\FollowerBotJYJ1\init.py", line 15, in init
    self.browser = uc.Chrome(options=chrome_options, version_main=108)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jharol.perez\Pictures\FollowerBotJYJ\env\Lib\site-packages\undetected_chromedriver\__init__.py", line 429, in __init__   
    super(Chrome, self).__init__(
  File "C:\Users\jharol.perez\Pictures\FollowerBotJYJ\env\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 80, in __init__ 
    super().__init__(
  File "C:\Users\jharol.perez\Pictures\FollowerBotJYJ\env\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 104, in __init__
    super().__init__(
  File "C:\Users\jharol.perez\Pictures\FollowerBotJYJ\env\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 286, in __init__    self.start_session(capabilities, browser_profile)
  File "C:\Users\jharol.perez\Pictures\FollowerBotJYJ\env\Lib\site-packages\undetected_chromedriver\__init__.py", line 715, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "C:\Users\jharol.perez\Pictures\FollowerBotJYJ\env\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jharol.perez\Pictures\FollowerBotJYJ\env\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute 
    self.error_handler.check_response(response)
  File "C:\Users\jharol.perez\Pictures\FollowerBotJYJ\env\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:54780
from session not created: This version of ChromeDriver only supports Chrome version 108
Current browser version is 110.0.5481.78
Stacktrace:
Backtrace:
        (No symbol) [0x0116F243]
        (No symbol) [0x010F7FD1]
        (No symbol) [0x00FED04D]
        (No symbol) [0x0100F6B4]
        (No symbol) [0x01008424]
        (No symbol) [0x01008201]
        (No symbol) [0x0103F056]
        (No symbol) [0x0103EB2A]
        (No symbol) [0x01038386]
        (No symbol) [0x0101163C]
        (No symbol) [0x0101269D]
        GetHandleVerifier [0x01409A22+2655074]
        GetHandleVerifier [0x013FCA24+2601828]
        GetHandleVerifier [0x01218C0A+619850]
        GetHandleVerifier [0x01217830+614768]
        (No symbol) [0x011005FC]
        (No symbol) [0x01105968]
        (No symbol) [0x01105A55]
        (No symbol) [0x0111051B]
        BaseThreadInitThunk [0x77A200F9+25]
        RtlGetAppContainerNamedObjectPath [0x77DB7BBE+286]
        RtlGetAppContainerNamedObjectPath [0x77DB7B8E+238]

Exception ignored in: <function Chrome.__del__ at 0x000000000642A0C0>
Traceback (most recent call last):
  File "C:\Users\jharol.perez\Pictures\FollowerBotJYJ\env\Lib\site-packages\undetected_chromedriver\__init__.py", line 769, in __del__    
  File "C:\Users\jharol.perez\Pictures\FollowerBotJYJ\env\Lib\site-packages\undetected_chromedriver\__init__.py", line 758, in quit       
OSError: [WinError 6] Controlador no válido
--------------------------------------------------------
Codigo init.py

from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
import warnings
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
import undetected_chromedriver as uc

class Setup:
    def init(self):
        chrome_options = uc.ChromeOptions()
        chrome_options.add_argument('--headless')
        self.browser = uc.Chrome(options=chrome_options, version_main=108)

    def close_browser(self):
        self.browser.close()

--------------------------

Requirements.txt

beautifulsoup4==4.11.1
webdriver-manager==3.8.2
webdrivermanager==0.10.0
selenium==4.8.0
undetected_chromedriver==3.1.7
webdriver_manager==3.8.2

-------------------

Version python 

Python 3.11.1

Help me please!

![Captura](https://user-images.githubusercontent.com/20784466/218109872-a874c076-8c94-481f-9a49-1b79d65c933c.PNG)

**Comment by asimptot** [comment]
Please write 110 instead of 108.

**Comment by jjharoll** [comment]
(env) C:\Users\jharol.perez\Desktop\FollowerBotJYJ1>python get_instagram_followers.py
What is your Instagram username?
jyj_press_on_nails_colombia
Getting followers... Please do not terminate the program.
Traceback (most recent call last):
  File "C:\Users\jharol.perez\Desktop\FollowerBotJYJ1\get_instagram_followers.py", line 46, in <module>
    ig.setup()
  File "C:\Users\jharol.perez\Desktop\FollowerBotJYJ1\get_instagram_followers.py", line 13, in setup   
    Setup.init(self)
  File "C:\Users\jharol.perez\Desktop\FollowerBotJYJ1\init.py", line 15, in init
    self.browser = uc.Chrome(options=chrome_options, version_main=110)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jharol.perez\Pictures\FollowerBotJYJ\env\Lib\site-packages\undetected_chromedriver\__init__.py", line 429, in __init__   
    super(Chrome, self).__init__(
  File "C:\Users\jharol.perez\Pictures\FollowerBotJYJ\env\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 80, in __init__ 
    super().__init__(
  File "C:\Users\jharol.perez\Pictures\FollowerBotJYJ\env\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 104, in __init__
    super().__init__(
  File "C:\Users\jharol.perez\Pictures\FollowerBotJYJ\env\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 286, in __init__    self.start_session(capabilities, browser_profile)
  File "C:\Users\jharol.perez\Pictures\FollowerBotJYJ\env\Lib\site-packages\undetected_chromedriver\__init__.py", line 715, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "C:\Users\jharol.perez\Pictures\FollowerBotJYJ\env\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jharol.perez\Pictures\FollowerBotJYJ\env\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\jharol.perez\Pictures\FollowerBotJYJ\env\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:56544
from unknown error: unable to discover open pages
Stacktrace:
Backtrace:
        (No symbol) [0x00B937D3]
        (No symbol) [0x00B28B81]
        (No symbol) [0x00A2B36D]
        (No symbol) [0x00A4ED6D]
        (No symbol) [0x00A470F0]
        (No symbol) [0x00A46EE1]
        (No symbol) [0x00A81ED5]
        (No symbol) [0x00A81B2C]
        (No symbol) [0x00A7B216]
        (No symbol) [0x00A50D97]
        (No symbol) [0x00A5253D]
        GetHandleVerifier [0x00E0ABF2+2510930]
        GetHandleVerifier [0x00E38EC1+2700065]
        GetHandleVerifier [0x00E3C86C+2714828]
        GetHandleVerifier [0x00C43480+645344]
        (No symbol) [0x00B30FD2]
        (No symbol) [0x00B36C68]
        (No symbol) [0x00B36D4B]
        (No symbol) [0x00B40D6B]
        BaseThreadInitThunk [0x77A200F9+25]
        RtlGetAppContainerNamedObjectPath [0x77DB7BBE+286]
        RtlGetAppContainerNamedObjectPath [0x77DB7B8E+238]

Exception ignored in: <function Chrome.__del__ at 0x000000000641A0C0>
Traceback (most recent call last):
  File "C:\Users\jharol.perez\Pictures\FollowerBotJYJ\env\Lib\site-packages\undetected_chromedriver\__init__.py", line 769, in __del__    
  File "C:\Users\jharol.perez\Pictures\FollowerBotJYJ\env\Lib\site-packages\undetected_chromedriver\__init__.py", line 758, in quit       
OSError: [WinError 6] Controlador no válido
![error1](https://user-images.githubusercontent.com/20784466/218117211-9c68d993-722b-499b-bcd5-7a4a5602bc74.PNG)

**Comment by asimptot** [comment]
Strange! Could you write 127, instead of 110, please? If it doesn't work, I have an alternative solution, as well.

**Comment by jjharoll** [comment]
![error2](https://user-images.githubusercontent.com/20784466/218121609-a484a553-fc6f-4d60-a813-39b3765ede52.PNG)
not yet friend

**Comment by jjharoll** [comment]
Excellent. applying solution the script worked
