### ISSUE TITLE
get_credit_on_KingdomLikes

### ISSUE THREAD

**Issue by arham837** [asimptot/FollowerBot#52]
Error while running script 

Traceback (most recent call last):
  File "C:\Users\mansh\Desktop\FollowerBot-main\FollowerBot-main\get_credit_on_KingdomLikes.py", line 30, in go_to_website
    yt_view = self.browser.find_element(By.XPATH, '//*[@id="idpage5"]/div/div[5]/button')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mansh\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 830, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mansh\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\mansh\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="idpage5"]/div/div[5]/button"}
  (Session info: headless chrome=110.0.5481.96)
Stacktrace:
Backtrace:
        (No symbol) [0x00EF37D3]
        (No symbol) [0x00E88B81]
        (No symbol) [0x00D8B36D]
        (No symbol) [0x00DBD382]
        (No symbol) [0x00DBD4BB]
        (No symbol) [0x00DF3302]
        (No symbol) [0x00DDB464]
        (No symbol) [0x00DF1215]
        (No symbol) [0x00DDB216]
        (No symbol) [0x00DB0D97]
        (No symbol) [0x00DB253D]
        GetHandleVerifier [0x0116ABF2+2510930]
        GetHandleVerifier [0x01198EC1+2700065]
        GetHandleVerifier [0x0119C86C+2714828]
        GetHandleVerifier [0x00FA3480+645344]
        (No symbol) [0x00E90FD2]
        (No symbol) [0x00E96C68]
        (No symbol) [0x00E96D4B]
        (No symbol) [0x00EA0D6B]
        BaseThreadInitThunk [0x762C7D69+25]
        RtlInitializeExceptionChain [0x7724BB9B+107]
        RtlClearBits [0x7724BB1F+191]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mansh\Desktop\FollowerBot-main\FollowerBot-main\get_credit_on_KingdomLikes.py", line 52, in <module>
    kl.go_to_website()
  File "C:\Users\mansh\Desktop\FollowerBot-main\FollowerBot-main\get_credit_on_KingdomLikes.py", line 39, in go_to_website
    surf = self.browser.find_element(By.XPATH, '//*[@id="idpage5"]/div/div[5]/button')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mansh\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 830, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mansh\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\mansh\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="idpage5"]/div/div[5]/button"}
  (Session info: headless chrome=110.0.5481.96)
Stacktrace:
Backtrace:
        (No symbol) [0x00EF37D3]
        (No symbol) [0x00E88B81]
        (No symbol) [0x00D8B36D]
        (No symbol) [0x00DBD382]
        (No symbol) [0x00DBD4BB]
        (No symbol) [0x00DF3302]
        (No symbol) [0x00DDB464]
        (No symbol) [0x00DF1215]
        (No symbol) [0x00DDB216]
        (No symbol) [0x00DB0D97]
        (No symbol) [0x00DB253D]
        GetHandleVerifier [0x0116ABF2+2510930]
        GetHandleVerifier [0x01198EC1+2700065]
        GetHandleVerifier [0x0119C86C+2714828]
        GetHandleVerifier [0x00FA3480+645344]
        (No symbol) [0x00E90FD2]
        (No symbol) [0x00E96C68]
        (No symbol) [0x00E96D4B]
        (No symbol) [0x00EA0D6B]
        BaseThreadInitThunk [0x762C7D69+25]
        RtlInitializeExceptionChain [0x7724BB9B+107]
        RtlClearBits [0x7724BB1F+191]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mansh\Desktop\FollowerBot-main\FollowerBot-main\get_credit_on_KingdomLikes.py", line 54, in <module>
    kl.close_browser()
  File "C:\Users\mansh\Desktop\FollowerBot-main\FollowerBot-main\get_credit_on_KingdomLikes.py", line 46, in close_browser
    Setup.close_browser(self)
    ^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Setup' has no attribute 'close_browser'

**Comment by asimptot** [comment]
Hi,

Can you send a ss of your init.py file?

**Comment by arham837** [comment]
init.py screen shot is attached . 
[https://ibb.co/xLmVmWC](url)
https://ibb.co/xLmVmWC

**Comment by asimptot** [comment]
You should add tab to close_browser function. Please check the init function in the above.

**Comment by arham837** [comment]
From where i can check ?

**Comment by asimptot** [comment]
<img width="737" alt="image" src="https://user-images.githubusercontent.com/18220180/219001338-74355031-9624-45f9-9bc2-1b9a6f0c1b0d.png">

See differences.

**Comment by arham837** [comment]
ok ok got it thanks and please tell me about add me fast bot how to use

**Comment by asimptot** [comment]
You should have Addmefast account and sub app accounts(Facebook, Instagram, Pinterest etc.). After you enter your credentials, you will gain credits.

**Comment by arham837** [comment]
I am getting this error

DevTools listening on ws://127.0.0.1:55405/devtools/browser/138aaee1-f32c-41e0-b845-ae6d35ebb800
Traceback (most recent call last):
  File "C:\Users\mansh\Desktop\FollowerBot-main\FollowerBot-main\get_credit_on_AddMeFast.py", line 958, in <module>
    amf.setup()
  File "C:\Users\mansh\Desktop\FollowerBot-main\FollowerBot-main\get_credit_on_AddMeFast.py", line 13, in setup
    username = self.browser.find_element(By.XPATH, '//*[@id="wrapper"]/section[2]/div/div[4]/form/div[1]/div[1]/input[1]')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mansh\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 830, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mansh\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Users\mansh\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="wrapper"]/section[2]/div/div[4]/form/div[1]/div[1]/input[1]"}
  (Session info: headless chrome=110.0.5481.100)
Stacktrace:
Backtrace:
        (No symbol) [0x008637D3]
        (No symbol) [0x007F8B81]
        (No symbol) [0x006FB36D]
        (No symbol) [0x0072D382]
        (No symbol) [0x0072D4BB]
        (No symbol) [0x00763302]
        (No symbol) [0x0074B464]
        (No symbol) [0x00761215]
        (No symbol) [0x0074B216]
        (No symbol) [0x00720D97]
        (No symbol) [0x0072253D]
        GetHandleVerifier [0x00ADABF2+2510930]
        GetHandleVerifier [0x00B08EC1+2700065]
        GetHandleVerifier [0x00B0C86C+2714828]
        GetHandleVerifier [0x00913480+645344]
        (No symbol) [0x00800FD2]
        (No symbol) [0x00806C68]
        (No symbol) [0x00806D4B]
        (No symbol) [0x00810D6B]
        BaseThreadInitThunk [0x75CC7D69+25]
        RtlInitializeExceptionChain [0x7759BB9B+107]
        RtlClearBits [0x7759BB1F+191]

**Comment by asimptot** [comment]
Please run it in non-headless mode and give feedback to me.

**Comment by arham837** [comment]
can you tell me code for running or process for running in non headless mode.

**Comment by arham837** [comment]
Logged in AddmeFast. Your current point is: 12
Traceback (most recent call last):
  File "C:\Users\Asus\Downloads\Compressed\FollowerBot-main\FollowerBot-main\get_credit_on_AddMeFast.py", line 960, in <module>
    amf.login_facebook()
  File "C:\Users\Asus\Downloads\Compressed\FollowerBot-main\FollowerBot-main\get_credit_on_AddMeFast.py", line 72, in login_facebook
    cookies = WebDriverWait(self.browser, 10).until(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        (No symbol) [0x00D837D3]
        (No symbol) [0x00D18B81]
        (No symbol) [0x00C1B36D]
        (No symbol) [0x00C4D382]
        (No symbol) [0x00C4D4BB]
        (No symbol) [0x00C83302]
        (No symbol) [0x00C6B464]
        (No symbol) [0x00C81215]
        (No symbol) [0x00C6B216]
        (No symbol) [0x00C40D97]
        (No symbol) [0x00C4253D]
        GetHandleVerifier [0x00FFABF2+2510930]
        GetHandleVerifier [0x01028EC1+2700065]
        GetHandleVerifier [0x0102C86C+2714828]
        GetHandleVerifier [0x00E33480+645344]
        (No symbol) [0x00D20FD2]
        (No symbol) [0x00D26C68]
        (No symbol) [0x00D26D4B]
        (No symbol) [0x00D30D6B]
        BaseThreadInitThunk [0x75EC7D69+25]
        RtlInitializeExceptionChain [0x772CBB9B+107]
        RtlClearBits [0x772CBB1F+191]

**Comment by arham837** [comment]
now this error is coming.

**Comment by asimptot** [comment]
Btw, can you open a new ticket? Because the title is wrong and I fixed your the previous problem.

**Comment by arham837** [comment]
Yes why not wait.
