### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by a2gx2** [asimptot/FollowerBot#53]
Getting followers... Please do not terminate the program.
Traceback (most recent call last):
  File "C:\Users\Edit\Desktop\FollowerBot-main\get_instagram_followers.py", line 46, in <module>
    ig.setup()
  File "C:\Users\Edit\Desktop\FollowerBot-main\get_instagram_followers.py", line 13, in setup
    Setup.init(self)
  File "C:\Users\Edit\Desktop\FollowerBot-main\init.py", line 15, in init
    self.browser = uc.Chrome(options=chrome_options, version_main=108)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edit\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 421, in __init__
    browser = subprocess.Popen(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\Edit\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Edit\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1433, in _execute_child
    args = list2cmdline(args)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Edit\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 608, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "<frozen os>", line 824, in fsdecode
TypeError: expected str, bytes or os.PathLike object, not NoneType

Help pls!

**Comment by asimptot** [comment]
Please apply this solution.

https://github.com/asimptot/FollowerBot/issues/39#issuecomment-1398057818

**Comment by a2gx2** [comment]
I did what you told me and now I have this error:
Traceback (most recent call last):
  File "C:\Users\Edit\Desktop\FollowerBot-main\get_instagram_followers.py", line 4, in <module>
    from init import *
  File "C:\Users\Edit\Desktop\FollowerBot-main\init.py", line 11
    def init(self):
    ^
IndentationError: expected an indented block after class definition on line 10

**Comment by asimptot** [comment]
Can you send your error in screenshot format? Becuase I don't see what happened in line 4 and 11 on your local.

**Comment by a2gx2** [comment]
![Captura de pantalla (15)](https://user-images.githubusercontent.com/125518819/220192314-2ae5a5a7-2c43-4791-81db-1eefef538aac.png)

**Comment by asimptot** [comment]
Please apply this solution.

https://github.com/asimptot/FollowerBot/issues/39#issuecomment-1398057818

**Comment by a2gx2** [comment]
![Captura de pantalla (16)](https://user-images.githubusercontent.com/125518819/220458857-7cd73506-d576-4edf-ba85-35d7a2b5195a.png)

**Comment by asimptot** [comment]
This error is not caused by my side. You should use TABs. Otherwise, Python doesn't allow to run your code.
