### ISSUE TITLE
get_instagram_followers.py error

### ISSUE THREAD

**Issue by SincerelyFair** [asimptot/FollowerBot#57]
I'm getting this after running your exact code:
```
Getting followers... Please do not terminate the program.
Traceback (most recent call last):
  File "C:\Users\fair\OneDrive\Desktop\FollowerBot-main\get_instagram_followers.py", line 46, in <module>
    ig.setup()
  File "C:\Users\fair\OneDrive\Desktop\FollowerBot-main\get_instagram_followers.py", line 13, in setup
    Setup.init(self)
  File "C:\Users\fair\OneDrive\Desktop\FollowerBot-main\init.py", line 15, in init
    self.browser = uc.Chrome(options=chrome_options, version_main=108)
  File "C:\Python310\lib\site-packages\undetected_chromedriver\__init__.py", line 429, in __init__
    super(Chrome, self).__init__(
  File "C:\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 80, in __init__
    super().__init__(
  File "C:\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 104, in __init__
    super().__init__(
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Python310\lib\site-packages\undetected_chromedriver\__init__.py", line 715, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:1152
from session not created: This version of ChromeDriver only supports Chrome version 108
Current browser version is 110.0.5481.104
Stacktrace:
Backtrace:
        (No symbol) [0x0044F243]
        (No symbol) [0x003D7FD1]
        (No symbol) [0x002CD04D]
        (No symbol) [0x002EF6B4]
        (No symbol) [0x002E8424]
        (No symbol) [0x002E8201]
        (No symbol) [0x0031F056]
        (No symbol) [0x0031EB2A]
        (No symbol) [0x00318386]
        (No symbol) [0x002F163C]
        (No symbol) [0x002F269D]
        GetHandleVerifier [0x006E9A22+2655074]
        GetHandleVerifier [0x006DCA24+2601828]
        GetHandleVerifier [0x004F8C0A+619850]
        GetHandleVerifier [0x004F7830+614768]
        (No symbol) [0x003E05FC]
        (No symbol) [0x003E5968]
        (No symbol) [0x003E5A55]
        (No symbol) [0x003F051B]
        BaseThreadInitThunk [0x75DE7D69+25]
        RtlInitializeExceptionChain [0x77C7BB9B+107]
        RtlClearBits [0x77C7BB1F+191]
```
**After changing chrome version in init.py file to 109:**
```
Getting followers... Please do not terminate the program.
Traceback (most recent call last):
  File "C:\Users\fair\OneDrive\Desktop\FollowerBot-main\get_instagram_followers.py", line 46, in <module>
    ig.setup()
  File "C:\Users\fair\OneDrive\Desktop\FollowerBot-main\get_instagram_followers.py", line 13, in setup
    Setup.init(self)
  File "C:\Users\fair\OneDrive\Desktop\FollowerBot-main\init.py", line 15, in init
    self.browser = uc.Chrome(options=chrome_options, version_main=109)
  File "C:\Python310\lib\site-packages\undetected_chromedriver\__init__.py", line 429, in __init__
    super(Chrome, self).__init__(
  File "C:\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 80, in __init__
    super().__init__(
  File "C:\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 104, in __init__
    super().__init__(
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Python310\lib\site-packages\undetected_chromedriver\__init__.py", line 715, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:1919
from unknown error: unable to discover open pages
Stacktrace:
Backtrace:
        (No symbol) [0x00FC6643]
        (No symbol) [0x00F5BE21]
        (No symbol) [0x00E5DA9D]
        (No symbol) [0x00E82911]
        (No symbol) [0x00E7A9D4]
        (No symbol) [0x00E7A7B1]
        (No symbol) [0x00EB6917]
        (No symbol) [0x00EB655C]
        (No symbol) [0x00EAFB76]
        (No symbol) [0x00E849C1]
        (No symbol) [0x00E85E5D]
        GetHandleVerifier [0x0123A142+2497106]
        GetHandleVerifier [0x012685D3+2686691]
        GetHandleVerifier [0x0126BB9C+2700460]
        GetHandleVerifier [0x01073B10+635936]
        (No symbol) [0x00F64A1F]
        (No symbol) [0x00F6A418]
        (No symbol) [0x00F6A505]
        (No symbol) [0x00F7508B]
        BaseThreadInitThunk [0x75DE7D69+25]
        RtlInitializeExceptionChain [0x77C7BB9B+107]
        RtlClearBits [0x77C7BB1F+191]
```

**Changed chrome version in init.py to 110:**
```
Getting followers... Please do not terminate the program.
Traceback (most recent call last):
  File "C:\Users\fair\OneDrive\Desktop\FollowerBot-main\get_instagram_followers.py", line 46, in <module>
    ig.setup()
  File "C:\Users\fair\OneDrive\Desktop\FollowerBot-main\get_instagram_followers.py", line 13, in setup
    Setup.init(self)
  File "C:\Users\fair\OneDrive\Desktop\FollowerBot-main\init.py", line 15, in init
    self.browser = uc.Chrome(options=chrome_options, version_main=110)
  File "C:\Python310\lib\site-packages\undetected_chromedriver\__init__.py", line 429, in __init__
    super(Chrome, self).__init__(
  File "C:\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 80, in __init__
    super().__init__(
  File "C:\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 104, in __init__
    super().__init__(
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Python310\lib\site-packages\undetected_chromedriver\__init__.py", line 715, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:2104
from unknown error: unable to discover open pages
Stacktrace:
Backtrace:
        (No symbol) [0x005237D3]
        (No symbol) [0x004B8B81]
        (No symbol) [0x003BB36D]
        (No symbol) [0x003DED6D]
        (No symbol) [0x003D70F0]
        (No symbol) [0x003D6EE1]
        (No symbol) [0x00411ED5]
        (No symbol) [0x00411B2C]
        (No symbol) [0x0040B216]
        (No symbol) [0x003E0D97]
        (No symbol) [0x003E253D]
        GetHandleVerifier [0x0079ABF2+2510930]
        GetHandleVerifier [0x007C8EC1+2700065]
        GetHandleVerifier [0x007CC86C+2714828]
        GetHandleVerifier [0x005D3480+645344]
        (No symbol) [0x004C0FD2]
        (No symbol) [0x004C6C68]
        (No symbol) [0x004C6D4B]
        (No symbol) [0x004D0D6B]
        BaseThreadInitThunk [0x75DE7D69+25]
        RtlInitializeExceptionChain [0x77C7BB9B+107]
        RtlClearBits [0x77C7BB1F+191]
```

**Comment by asimptot** [comment]
Please apply this solution.

https://github.com/asimptot/FollowerBot/issues/39#issuecomment-1398057818

**Comment by SincerelyFair** [comment]
I've fixed that by updating to the latest lib versions and not specifying chrome version in init.py file and it works
One more thing is that my terminal was printing "An error has been occurred. Retrying...", found out that the XPaths in the website changed and was causing the browser to close automatically
Here is how it it for me right now:
     
 ```
        uid = self.browser.find_element(By.XPATH, '/html[1]/body[1]/div[3]/div[2]/div[2]/form[1]/div[1]/div[1]/input[1]')
        uid.send_keys(username)
        sleep(2)

        button = self.browser.find_element(By.XPATH, '/html[1]/body[1]/div[3]/div[2]/div[2]/form[1]/div[1]/div[3]/button[1]')
        button.click()

        element_present = EC.presence_of_element_located((By.XPATH, '/html/body/div[3]/div[2]/div[2]/div/div/a[1]/div'))
        WebDriverWait(self.browser, 1000).until(element_present)
```
Not sure if the last element is the same as the one in your code though but I appreciate your help
