### ISSUE TITLE
get_credit_on_AddMeFast.py

### ISSUE THREAD

**Issue by nardbyte** [asimptot/FollowerBot#66]
Im getting this error when i execute get_credit_on_AddMeFast.py:

```
DevTools listening on ws://127.0.0.1:54586/devtools/browser/3b1afcd4-dd6a-4f09-b804-7ac8a0d2bc35
Logged in AddmeFast. Your current point is: 8
Traceback (most recent call last):
  File "C:\Coding\FollowerBot\get_credit_on_AddMeFast.py", line 960, in <module>
    amf.login_facebook()
  File "C:\Coding\FollowerBot\get_credit_on_AddMeFast.py", line 72, in login_facebook
    cookies = WebDriverWait(self.browser, 10).until(
  File "C:\Python\lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message
```

Please help me for fix it, and thanks for share.

**Comment by asimptot** [comment]
Can you run it in non headless mode and send the screenshot of your browser please?

**Comment by nardbyte** [comment]
Hi im sorry for my late response,
Update:
The script crash here
![Screenshot_1](https://user-images.githubusercontent.com/22382010/229360473-a5cc151e-6514-4932-b75b-ca4dde38e207.png)

And this is the error:

Exception ignored in: <function Chrome.__del__ at 0x000001EF49C85800>
PS C:\Coding\FollowerBot> py get_credit_on_AddMeFast.py
Logged in AddmeFast. Your current point is: 8
Traceback (most recent call last):
  File "C:\Coding\FollowerBot\get_credit_on_AddMeFast.py", line 1046, in <module>
    amf.login_facebook()
  File "C:\Coding\FollowerBot\get_credit_on_AddMeFast.py", line 89, in login_facebook
    cookies = WebDriverWait(self.browser, 10).until(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nardb\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        (No symbol) [0x007A37D3]
        (No symbol) [0x00738B81]
        (No symbol) [0x0063B36D]
        (No symbol) [0x0066D382]
        (No symbol) [0x0066D4BB]
        (No symbol) [0x006A3302]
        (No symbol) [0x0068B464]
        (No symbol) [0x006A1215]
        (No symbol) [0x0068B216]
        (No symbol) [0x00660D97]
        (No symbol) [0x0066253D]
        GetHandleVerifier [0x00A1ABF2+2510930]
        GetHandleVerifier [0x00A48EC1+2700065]
        GetHandleVerifier [0x00A4C86C+2714828]
        GetHandleVerifier [0x00853480+645344]
        (No symbol) [0x00740FD2]
        (No symbol) [0x00746C68]
        (No symbol) [0x00746D4B]
        (No symbol) [0x00750D6B]
        BaseThreadInitThunk [0x76A07D69+25]
Exception ignored in: <function Chrome.__del__ at 0x000001530DE15800>
Traceback (most recent call last):
  File "C:\Users\nardb\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 769, in __del__
  File "C:\Users\nardb\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 758, in quit
OSError: [WinError 6] The handle is invalid
Exception ignored in: <function Patcher.__del__ at 0x000001530DE14AE0>
Traceback (most recent call last):
  File "C:\Users\nardb\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\patcher.py", line 273, in __del__
OSError: [WinError 6] The handle is invalid

**Comment by asimptot** [comment]
the same problem as https://github.com/asimptot/FollowerBot/issues/54 . Please apply and give fb to me.
